### ISSUE TITLE
Alternatively use GITHUB_PAT

### ISSUE THREAD

**Issue by jonocarroll** [ropensci/ghql#11]
`GITHUB_PAT` has been adopted by [`git2r`](https://github.com/ropensci/git2r/) and [`usethis`](https://github.com/r-lib/usethis) as the environment setting for a GitHub PAT. It might be useful to integrate that into `ghql` (even if only optionally) as many users will already have this set. At present, they will also need to set `GITHUB_GRAPHQL_TOKEN`, potentially to the same value.

(*) My understanding is that both of these environment variables intend to store the same authentication, so reducing duplication seems worthwhile. There may (for all I know) be reasons to store these separately, so perhaps adding some logic to search for one or the other (giving one precedence) is still worthwhile.

This would have a flow-on effect to packages which also use `ghql`, e.g. [`ghrecipes`](https://github.com/ropenscilabs/ghrecipes) (@maelle) and [`stellar`](https://github.com/ropenscilabs/stellar) (@mpadge).

**Comment by jonocarroll** [comment]
Ah, now I see. Entirely my bad. It does appear that `stellar` has freedom to set this name.

I agree that allowing for different scopes is useful. My suggestion would then be for packages using `ghql` to allow for one or the other (or arbitrary) with precedence, e.g.

```r
## use env_var with precedence, if present
## otherwise use GITHUB_GRAPHQL_TOKEN with precedence, if present
## otherwise use GITHUB_PAT, if present
## otherwise fail
get_token <- function(env_var = "") {
  token <- sapply(c(env_var, "GITHUB_GRAPHQL_TOKEN", "GITHUB_PAT"), Sys.getenv)
  token <- token[token != ""][1]
  if (is.na(token)) stop("NO TOKEN FOUND")
  token
}
```

I don't know if this would be useful here. For now I'll add this to `stellar`.

**Comment by mpadge** [comment]
If I may chip in here: I suspect ROpenSci could and should expect increasing numbers of submissions using the github API, and so it might be useful to consider ROpenSci suggesting/"enforcing" a standardized nomenclature for these tokens. I concur with @sckott that separate nomenclature for API3 vs API4 will likely be both necessary and useful, as it does seem that github has that in mind (even though current implementation appears not to distinguish - v4 responds same way to requests submitted with a v3 token). Now my one thought: `"_PAT"` is an obfuscatory acronym that should be avoided. It's just a token, so `"_TOKEN"` should be encouraged over `"_PAT". That would leave:

1. Generic `"_GITHUB_TOKEN"` for v3/standard use if no other found;
2. `"_GITHUB_GRAPHQL_TOKEN"` for v4 / override first for graphql queries.

**Comment by sckott** [comment]
Seems like we agree on some things:

- even if the same token will work for v3 and v4, different scopes may be needed in different cases, so different token env var names should be supported
- i agree that `PAT` is not a great thing for newcomers and should be changed to `TOKEN`
- i think that makes sense @mpadge when in a package where graphql queries are being used, look for `GITHUB_GRAPHQL_TOKEN` first, and if not found look for `GITHUB_TOKEN`.  And when a pkg is doing v3 queries just look for `GITHUB_TOKEN`. There is the issue though that the rstudio folks use `GITHUB_PAT`. thoughts?

How do people feel about allow users to pass in tokens to functions? I usually allow this, but strongly encourage users not to do that, unless its passed in like `token = Sys.getenv('token ...')`. The safer thing to prevent users from shooting themselves in the foot would be only to support setting an env var in your .Renviron/etc. - but I imagine many R users would find that too cumbersome

**Comment by mpadge** [comment]
Yeah, @sckott double-agree back at ya on all dot points. Re: RStudio: My opintion would be that that's a rare mistake on their part: It really should be `"TOKEN"`, not `"PAT"`. ROpenSci has a chance to lead the foremost open community in this regard. I actually envision a kinda master policy on environmental variables, token nomenclature, and the likes. It could easily be started by a simple scrape of all current ROpenSci kind for all envvars set and used to collate an initial list.

That of course necessitates and leads to the need for a conveneient package-based management system, because yeah, directly setting `.Renviron` or whatever is indeed overly burdensome. @gaborcsardi's [`dotenv`](https://github.com/gaborcsardi/dotenv) package is the best thing I'm aware of in this regard - cleverly sticks em all in a `.env` file, rather than appending to `.Renviron`.

Final thought: Never permit passing API tokens as args, coz that only encourages pasting them in scripts which is [... insert list of negative adjectives ...]

**Comment by sckott** [comment]
Yeah, I'm all for `_TOKEN`

Interesting, I'd not heard of a `.env` file before now. Is this a convention of some kind?

> Never permit passing API tokens as args

I can see how this would be a definite **YES** if we were in a community where most users are developers, but I worry that the first experience of a pkg that requires a secret may be hard for some. Maybe a compromise could be allow passing in secrets, but throw a warning/message telling user to set key as env var (and then not throw the warning/message when they've done so)?

**Comment by cboettig** [comment]
There's some subtle issues here, wondering if it would be good to have a quick run through of these in the unconf issues thread?  A master policy on token management and some user-friendly tools for token wrangling would be awesome.  

For instance, I'm not sure it's a good idea not to allow tokens in arguments; what if I want to loop over a task on a bunch of different accounts with different tokens?  Or call a function through the opencpu API?  In general it's nice that function arguments are (optional) arguments.  Of course these should read from the env var by default, but I think it's more of a matter of documentation to encourage best practice.  After all, a careless user can still put `options()` or `Sys.setenv()` in a script.

The naming one is tough too.  I see about 78K hits for `GITHUB_TOKEN` (about 1K from R), 34K for `GH_TOKEN` and only 1K for `GITHUB_PAT` on a GitHub search (about 500 of which are from R), so I guess `GITHUB_TOKEN` is the clear winner.  Of course it's often wiser to use multiple tokens depending on the permission level needed etc, but perhaps that is better managed with some token-management tool rather than an app-specific name for the token.  just my 2c, sorry to jump in here.

**Comment by mpadge** [comment]
Token nomenclature is only important here in examples and package documentation. Users can name their tokens whatever they want, since these must be explicitly passed to the constructors anyway. All documentation has been updated to use `GITHUB_TOKEN` for consistency with GitHub actions.
